theme: jekyll-theme-cayman
title: Panda_2134's Blog
tag: Stay Hungry, Stay Stupid
highlighter: rouge
author: panda_2134
permalink: /:year/:month/:day/:title
excerpt_separator: <!--more-->
markdown: kramdown