theme: jekyll-theme-cayman
title: Panda_2134's Blog
markdown: kramdown
highlighter: rouge
author: panda_2134
permalink: /:year/:month/:day/:title
excerpt_separator: <!--more-->
defaults:
  -
    scope:
      path: "" 
    values:
      layout: "post"
	comments: true
